### ISSUE TITLE
Program Crashes on Windows 10 April 2018 Update

### ISSUE THREAD

**Issue by stephenej** [Kalejin/DCSB#20]
Program fails to run after updating to Windows 10 April 2018 Update.
Below are the two Event Logs generated whenever trying to run the program.
I have reinstalled, removed settings (that I could find including the config.xml in ProgramData), ran dism and sfc to verify system files.
I also tried running it as an Admin, using compatibility settings (Win 8, 7, etc) and none of these helped.
I even tried compiling from source to see if something was dependent upon some system file or anything and that of course didn't help either.

Rolled back to 4.0.0.3 and it runs, so something happened after that version.

Thanks for making such an awesome program and I look forward to any help provided.

Application Error:
Faulting application name: DCSB.exe, version: 4.0.0.6, time stamp: 0x5ab8a3eb
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1, time stamp: 0x149ab0fd
Exception code: 0xe0434352
Fault offset: 0x0010d722
Faulting process id: 0x34d4
Faulting application start time: 0x01d3e131483d4c2a
Faulting application path: C:\Program Files (x86)\Deathcounter and Soundboard\DCSB.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2965388b-0d6a-42a6-95fb-8f9e0b3b71b7
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime:
Application: DCSB.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at NAudio.CoreAudioApi.Interfaces.IPropertyStore.GetValue(NAudio.CoreAudioApi.PropertyKey ByRef, NAudio.CoreAudioApi.Interfaces.PropVariant ByRef)
   at NAudio.CoreAudioApi.PropertyStore.get_Item(NAudio.CoreAudioApi.PropertyKey)
   at NAudio.CoreAudioApi.MMDevice.get_FriendlyName()
   at DCSB.SoundPlayer.AudioPlaybackEngine+<>c__DisplayClass20_0.<EnumerateDevices>b__0(NAudio.CoreAudioApi.MMDevice)
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at DCSB.SoundPlayer.AudioPlaybackEngine.EnumerateDevices()
   at DCSB.Business.SoundManager.GetDevice(System.String, Boolean)
   at DCSB.Business.SoundManager.InstantiateDevice(System.String, Boolean, DCSB.SoundPlayer.AudioPlaybackEngine ByRef)
   at DCSB.Business.SoundManager.ChangeDevice(System.String, Single, DCSB.SoundPlayer.AudioPlaybackEngine ByRef)
   at DCSB.Business.SoundManager..ctor(DCSB.Models.ConfigurationModel)
   at DCSB.ViewModels.ViewModel..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at DCSB.App.Main()

**Comment by Kalejin** [comment]
Hi,
could you please try version 4.0.0.7 ?
I added displaying error message to unhandled exceptions and it should provide some more information than Windows Event logs.

**Comment by stephenej** [comment]
Here is the window that running it returns (cannot select text so image attached):
![image](https://user-images.githubusercontent.com/5493213/39547469-b185fdcc-4e25-11e8-94b9-6fcac3b0a7a3.png)

Event Logs:

Application Error:
Faulting application name: DCSB.exe, version: 4.0.0.7, time stamp: 0x5ae9b72d
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1, time stamp: 0x149ab0fd
Exception code: 0xe0434352
Fault offset: 0x0010d722
Faulting process id: 0x5688
Faulting application start time: 0x01d3e253da3b30a5
Faulting application path: C:\Program Files (x86)\Deathcounter and Soundboard\DCSB.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8330149e-7c6a-4bb1-92a2-990fd7e892f1
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime:
Application: DCSB.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at NAudio.CoreAudioApi.Interfaces.IPropertyStore.GetValue(NAudio.CoreAudioApi.PropertyKey ByRef, NAudio.CoreAudioApi.Interfaces.PropVariant ByRef)
   at NAudio.CoreAudioApi.PropertyStore.get_Item(NAudio.CoreAudioApi.PropertyKey)
   at NAudio.CoreAudioApi.MMDevice.get_FriendlyName()
   at DCSB.SoundPlayer.AudioPlaybackEngine+<>c__DisplayClass20_0.<EnumerateDevices>b__0(NAudio.CoreAudioApi.MMDevice)
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at DCSB.SoundPlayer.AudioPlaybackEngine.EnumerateDevices()
   at DCSB.Business.SoundManager.GetDevice(System.String, Boolean)
   at DCSB.Business.SoundManager.InstantiateDevice(System.String, Boolean, DCSB.SoundPlayer.AudioPlaybackEngine ByRef)
   at DCSB.Business.SoundManager.ChangeDevice(System.String, Single, DCSB.SoundPlayer.AudioPlaybackEngine ByRef)
   at DCSB.Business.SoundManager..ctor(DCSB.Models.ConfigurationModel)
   at DCSB.ViewModels.ViewModel..ctor()
   at DCSB.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at DCSB.App.Main()

**Comment by Kalejin** [comment]
Could you please try version 4.0.0.8?
It should resolve your issues, although it may be a problem with drivers and in that case there is not much I can do.

**Comment by stephenej** [comment]
Works flawlessly.

**Comment by Kalejin** [comment]
I am glad to hear that :)
Resolved in commit 56a4835
